name: Checkov IaC Scan

on:
  push:
    branches:
      - master
    paths:
      - '**/*.tf'
      - '**/*.yml'
      - '**/*.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.yml'
      - '**/*.yaml'

jobs:
  checkov_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Checkov
      run: pip install checkov

    - name: Run Checkov scan and generate HTML report
      run: checkov -d . --output html > checkov_report.html

    - name: Upload Checkov report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: checkov-report
        path: checkov_report.html
